AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Youtube Outline API Lambda Functions

Globals:
  Function:
    Timeout: 60
    MemorySize: 256
    Runtime: python3.11
    Environment:
      Variables:
        OPENAI_API_KEY: !Sub '{{resolve:secretsmanager:${OpenAISecretName}}}'

Parameters:
  OpenAISecretName:
    Type: String
    Description: Name of the secret containing the OpenAI API key

Resources:
  GetTranscriptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: get_transcript.handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /transcript
            Method: post

  GenerateQuizFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: generate_quiz.handler
      Timeout: 300  # 5 minutes for quiz generation
      MemorySize: 512  # More memory for LLM operations
      Events:
        Api:
          Type: Api
          Properties:
            Path: /quiz
            Method: post

  GenerateSummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: generate_summary.handler
      Timeout: 300  # 5 minutes for summary generation
      MemorySize: 512  # More memory for LLM operations
      Events:
        Api:
          Type: Api
          Properties:
            Path: /summary
            Method: post

Outputs:
  ApiURL:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
